# rundeck-ansible 

version: '3.9'

services:

    rundeck:
        build:
            context: .
        hostname: rundeck
        restart: unless-stopped
        depends_on:
            - postgres
        ports:
            - 4440:4440
            - 8080:8080
        volumes:
            - ansible-data:/home/rundeck/ansible
            - rundeck-data:/home/rundeck/server/data

    postgres:
        image: postgres:15.3-alpine3.18
        restart: unless-stopped
        ports:
          - 5432:5432
        volumes:
          - postgres-data:/var/lib/postgresql/data

    pgadmin4:
        image: dpage/pgadmin4:7.4
        restart: unless-stopped
        ports:
          - 5050:5050
        depends_on:
            - postgres
        
volumes:
  postgres-data:
  ansible-data:
  rundeck-data:
